config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'roots#top'
    get "/"=>"root#top"

get 'topics/index'
  get 'topics/show/:id' => 'topics#show', as: :topics_show
  post 'topics/create' => 'topics#create'
  delete 'topics/delete/:id' => 'topics#delete', as: :topic_delete
  post 'posts/create' => 'post#create', as: :post_create
  resources :users,only: [:show,:edit,:update,:destroy,:info] 
    resources :subs,only: [:new,:index,:show] 
     post 'subs/create' => 'subs#create'
     resources :cons,only: [:new,:index,:show]
          post 'cons/create' => 'cons#create'
          mount ActionCable.server => '/cable'
          # mount ActionCable.server => '/cable'
    end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/con.rb
class Con < ApplicationRecord
	default_scope -> { order(created_at: :desc) }
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :from, class_name: "User"
belongs_to :to, class_name: "User"
# Scopes
default_scope -> {order(created_at: :asc)}

# Validations
validates :from_id, presence: true
validates :to_id, presence: true
validates :room_id, presence: true
validates :content, presence: true, length: {maximum: 50}

# Methods
def Message.recent_in_room(room_id)
  where(room_id: room_id).last(500)
end
after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
end

app/models/sub.rb
class Sub < ApplicationRecord
default_scope -> { order(created_at: :desc) }
belongs_to :user


end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :from_messages, class_name: "Message",
          foreign_key: "from_id", dependent: :destroy
has_many :to_messages, class_name: "Message",
          foreign_key: "to_id", dependent: :destroy
has_many :sent_messages, through: :from_messages, source: :from
has_many :received_messages, through: :to_messages, source: :to
has_many :topics
has_many :subs

attachment :profile_image
# Send message to other user
def send_message(other_user, room_id, content)
  from_messages.create!(to_id: other_user.id, room_id: room_id, content: content)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    root_path
  end
  def after_sign_up_path_for(resource)
    root_path
  end
  def after_sign_out_path_for(resource)
    root_path
  end

before_action :set_current_user

def set_current_user
  @current_user = User.find_by(id: session[:user_id])
end
  before_action :configure_permitted_parameters, if: :devise_controller? 
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:post,:address])
  end
end

app/controllers/cons_controller.rb
class ConsController < ApplicationController 

def index
	@cons = Con.all
end

def show
  @con = Con.find(params[:id])
	end
	

 def new

    @newCon = Con.new
  end
 def create
    @con = Con.new(params[:con].permit(:title,:job,:body,:address))
    @con.save
    redirect_to cons_path
  end
 end

app/controllers/post_controller.rb
class PostController < ApplicationController

  def create
    @post = Post.new(params[:post].permit(:topic_id, :name, :body))
    @post.save
    redirect_to topics_show_path(params[:post]['topic_id'])
  end

end

app/controllers/posts_controller.rb
class PostController < ApplicationController

  def create
    @post = Post.new(params[:post].permit(:topic_id, :name, :body))
    @post.save
    redirect_to topics_show_path(params[:post]['topic_id'])
  end

end

app/controllers/roots_controller.rb
class RootsController < ApplicationController
  def top

end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController 

def index
	@subs = Sub.all
end

def show
  @sub = Sub.find(params[:id])
	end
	
 def new
    @newSub = Sub.new
  end
 def create
    @sub = Sub.new(params[:sub].permit(:title,:job,:body,:address))
    @sub.save
    redirect_to subs_path
  end
 end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
    @newTopic = Topic.new
    @users = User.all
  end

  def show
    @topic = Topic.find(params[:id])
    @newpost = Post.new(:topic_id => params[:id])
    @posts = Post.where(topic_id: params[:id])
  end

  def create
    @topic = Topic.new(params[:topic].permit(:title,:job,:body,:user_id))
    @topic.user_id = current_user.id
    @topic.save
    redirect_to topics_index_path
  end

  def delete
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_index_path
  end

private
def topic_params
    params.require(:topic).permit(:title, :body, :user_id)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: :destroy

  def show
      @user = User.find(params[:id])
    if @user == current_user or current_user.admin?
    else
       redirect_to user_path(current_user)
  end
end

  def edit
    @user = User.find(params[:id])
    if @user == current_user or current_user.admin?
    else
       redirect_to user_path(current_user), notice: '変更出来ませんでした'
    end
  end
  def update
     user = User.find(params[:id])
        user.update(user_params)
        redirect_to user_path(user.id), notice: '変更完了'
  end
  def destroy
    user = User.find(params[:id])
      if user.admin?
         redirect_to admin_users_path, notice: '管理者は削除出来ません'
      else
         user.destroy
         redirect_to admin_users_path, notice: '削除完了'
      end
  end

  def favorites
    @user = User.find_by(id: params[:user_id])
    @favorites = Favorite.where(user_id: @user.id).all
  end

  private
  def user_params
    params.require(:user).permit(:name,:kana,:tel,:address,:post,:email,:encrypted_password,:profile_image)
  end
  def admin_user
   redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/chats/index.html.slim
h1 = "#{@user.name }のタイムライン"
                                                                                                                                                                        input#message-box[type="text"]
input#send-btn[type="submit" value="送信"]

table#chat-table

coffee:

  App.chat = App.cable.subscriptions.create "ChatChannel",
    connected: ->

    disconnected: ->

    received: (data) ->
      $('#chat-table').prepend("<tr><th>#{data.name}</th><td>#{data.content}</td></tr>")

    new_message: (message) ->
      @perform 'create_message', {message: message}

  $('#send-btn').on 'click',  ->
    App.chat.new_message $('#message-box').val()

app/views/cons/index.html.erb
<div class="container">
	<div class="row">

		<div class="topics">
			<div class="col-sm-3 sub2">
		<%= link_to new_con_path do %>
                <button type="button" class="square_btn1">下請けを募集する</button>
            <% end %>
            <%= link_to new_con_path do %>
                <button type="button" class="square_btn1">元請けを募集する</button>
            <% end %>
</div>

<div class="col-sm-offset-4">
			<div class="topicform">
		<% @cons.each do |con| %>

						<div class="topics1">
							<div class="posttitle"><%= link_to con.title ,con_path(con.id) %>
							</div>


							<p class="mitumori">＿</p>
							<div class="taiou ">	<p>対応工事</p> <%= con.job %>
<p>現場住所</p><%= con.address %></div>
<%= link_to con_path(con.id) do %>
                <button type="button" class="square_btn3">詳細をみる</button>
            <% end %>




						</div>

					<% end %>
					</div>
					</div>
					</div></div></div>

app/views/cons/new.html.erb
<div class="container">
	<div class="row">

		<div class="topics">
<div class="col-sm-3 sub2">
		<%= link_to new_sub_path do %>
                <button type="button" class="square_btn1">下請けを募集する</button>
            <% end %>
            <%= link_to new_con_path do %>
                <button type="button" class="square_btn1">元請けを募集する</button>
            <% end %>
</div>
<div class="col-sm-offset-4">
<p class="sub">元請会社募集・空き業者情報を登録する</p>


				<%= form_for @newCon, :url => {:action => 'create'} do |f| %>
				<p class="sub">募集詳細／工事内容</p>
				<%= f.text_area :body ,rows: 8 ,cols:80%>

				<hr>
				<p class="sub">現場住所</p>
				<div class="cp_ipselect cp_sl01">
  <%= f.select :address, [["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"],["福島県", "福島県"],["茨城県", "茨城県"],["栃木県", "栃木県"],["群馬県", "群馬県"],["埼玉県", "埼玉県"],["千葉県", "千葉県"],["東京都", "東京都"],["神奈川県", "神奈川県"],["新潟県", "新潟県"],["富山県", "富山県"],["石川県", "石川県"],["福井県", "福井県"],["山梨県", "山梨県"],["長野県", "長野県"],["岐阜県", "岐阜県"],["静岡県", "静岡県"],["愛知県", "愛知県"],["三重県", "三重県"],["滋賀県", "滋賀県"],["京都府", "京都府"],["大阪府", "大阪府"],["兵庫県", "兵庫県"],["奈良県", "奈良県"],["和歌山県", "和歌山県"],["鳥取県", "鳥取県"],["島根県", "島根県"],["岡山県", "岡山県"],["広島県", "広島県"],["山口県", "山口県"],["徳島県", "徳島県"],["香川県", "香川県"],["愛媛県", "愛媛県"],["高知県", "高知県"],["福岡県", "福岡県"],["佐賀県", "佐賀県"],["長崎県", "長崎県"],["熊本県", "熊本県"],["大分県", "大分県"],["宮崎県", "宮崎県"],["	鹿児島県", "	鹿児島県"],["沖縄県", "沖縄県"]]  ,class:"form-control" %></div>


				<hr>

				<p class="sub">工事種別</p>
				<div class="cp_ipselect cp_sl01">
  <%= f.select :job, [["土木工事業", "土木工事業"], ["建築工事業", "建築工事業"], ["大工工事業", "大工工事業"], ["左官工事業", "左官工事業"], ["とび工事業", "とび工事業"], ["石工事業", "石工事業"]] ,class:"form-control" %></div>


				<br>

				<br>
				<br>
				<%= f.submit %>

				<% end %>
				
				</div>
			</div>
		</div>
	</div>

app/views/cons/show.html.erb
<div class="topics2">
<div class="container">
	<div class="row">
		<div class="topics">

		<div class="col-sm-3 sub2">
		<%= link_to new_sub_path do %>
                <button type="button" class="square_btn1">下請けを募集する</button>
            <% end %>
            <%= link_to new_con_path do %>
                <button type="button" class="square_btn1">元請けを募集する</button>
            <% end %>

</div>
<div class="col-sm-offset-4">
			<div class="topicform">


						<h3><%= @con.title  %></h3>
						<div>

<ul>
            <li>
                <dl>
                    <dt>工事内容</dt>
                    <dd><%= @con.body  %></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>現場住所</dt>
                    <dd>
                       <%= @con.address  %>
                    </dd>
                </dl>
            </li>
           
        </ul>




						</div>
</div>

					</div>
					</div>
					</div></div></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KNetWork</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
  <div>
 <img src="/assets/logo.jpg" alt=" " class="col-sm-1 img4" />
 <div class="head col-sm-1">
 <%= link_to 'ホーム', root_path, class: "i far fa-star" %>
 </div>
 
  <div class="head col-sm-1">
  <%= link_to '掲示板', topics_index_path, class: "i far fa-star" %>
  </div>
   <% if user_signed_in? %>
   <div class="head col-sm-1">
  <%= link_to 'マイページ', user_path(current_user), class: "i far fa-star" %>
  <%end%>
  </div>
   <div class="head col-sm-1">
  <%= link_to '下請け募集', subs_path, class: "i far fa-star" %>
  </div>
  <div class="head col-sm-1">
  <%= link_to '元請け募集', cons_path, class: "i far fa-star" %>
  </div>
  <div class="head col-sm-2">
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "i far fa-star" %>
  </div>

</div></div></div>

  </header>


  <body>
    <%= yield %>
  </body>

  <footer>
  <div class="footer1"></div>
  <div class="footer2"></div>
    
  </footer>
</html>

app/views/messages/_message.html.erb
<div class="message" data-session="<%= session[:user_id] %>">
  <% user = User.find_by(id: message.from_id) %>
  <p class="<%= message.id %>" id="message_sender"><%= user.name %></p>
  <p class="<%= message.id %>" id="message_content"><%= message.content %></p>
  <script type="text/javascript">
    var from_id = <%= message.from_id %>;
    var current_user_id = $('.message').data('session');
    if(from_id == current_user_id){
      $('p.' + <%= message.id %>).css('text-align', 'right');
    }else{
      $('p.' + <%= message.id %>).css('text-align', 'left');
    }
  </script>
</div>

app/views/messages/_message_form.html.erb
<form class="message_form">
  <input type="hidden" name="from_id" value="<%= from_user.id %>">
  <input type="hidden" name="to_id" value="<%= to_user.id %>">
  <input type="hidden" name="room_id" value="<%= room_id %>">
  <label>Send Message to <%= to_user.name %></label><br>
  <input type="text" name="content" data-behavior="chat_speaker">
</form>

app/views/subs/index.html.erb
<div class="container">
	<div class="row">

		<div class="topics">
			<div class="col-sm-3 sub2">
		<%= link_to new_sub_path do %>
                <button type="button" class="square_btn1">下請けを募集する</button>
            <% end %>
            <%= link_to new_con_path do %>
                <button type="button" class="square_btn1">元請けを募集する</button>
            <% end %>
</div>

<div class="col-sm-offset-4">
			<div class="topicform">
		<% @subs.each do |sub| %>

						<div class="topics1">
							<div class="posttitle"><%= link_to sub.title ,sub_path(sub.id) %>
							</div>


							<p class="mitumori"><b>見積もり希望</b></p>
							<div class="taiou ">	<p>対応工事</p> <%= sub.job %>
<p>現場住所</p><%= sub.address %></div>
<%= attachment_image_tag sub.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", :size => "40x40" %>

<%= link_to sub_path(sub.id) do %>
                <button type="button" class="square_btn3">詳細をみる</button>
            <% end %>




						</div>

					<% end %>
					</div>
					</div>
					</div></div></div>

app/views/subs/new.html.erb
<div class="container">
	<div class="row">

		<div class="topics">
<div class="col-sm-3 sub2">
		<%= link_to new_sub_path do %>
                <button type="button" class="square_btn1">下請けを募集する</button>
            <% end %>
            <%= link_to new_con_path do %>
                <button type="button" class="square_btn1">元請けを募集する</button>
            <% end %>
</div>
<div class="col-sm-offset-4">
<p class="sub">下請業者募集・工事案件を依頼する</p>

<hr>
				<%= form_for @newSub, :url => {:action => 'create'} do |f| %>
				<p class="sub">タイトル</p>
				<%= f.text_area :title,rows: 1 ,cols:80 %>
				<hr>
				<p class="sub">募集詳細／工事内容</p>
				<%= f.text_area :body ,rows: 8 ,cols:80%>

				<hr>
				<p class="sub">現場住所</p>
				<div class="cp_ipselect cp_sl01">
  <%= f.select :address, [["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"],["福島県", "福島県"],["茨城県", "茨城県"],["栃木県", "栃木県"],["群馬県", "群馬県"],["埼玉県", "埼玉県"],["千葉県", "千葉県"],["東京都", "東京都"],["神奈川県", "神奈川県"],["新潟県", "新潟県"],["富山県", "富山県"],["石川県", "石川県"],["福井県", "福井県"],["山梨県", "山梨県"],["長野県", "長野県"],["岐阜県", "岐阜県"],["静岡県", "静岡県"],["愛知県", "愛知県"],["三重県", "三重県"],["滋賀県", "滋賀県"],["京都府", "京都府"],["大阪府", "大阪府"],["兵庫県", "兵庫県"],["奈良県", "奈良県"],["和歌山県", "和歌山県"],["鳥取県", "鳥取県"],["島根県", "島根県"],["岡山県", "岡山県"],["広島県", "広島県"],["山口県", "山口県"],["徳島県", "徳島県"],["香川県", "香川県"],["愛媛県", "愛媛県"],["高知県", "高知県"],["福岡県", "福岡県"],["佐賀県", "佐賀県"],["長崎県", "長崎県"],["熊本県", "熊本県"],["大分県", "大分県"],["宮崎県", "宮崎県"],["	鹿児島県", "	鹿児島県"],["沖縄県", "沖縄県"]] ,class:"form-control" %></div>


				

				<hr>

				<p class="sub">工事種別</p>
				<div class="cp_ipselect cp_sl01">
  <%= f.select :job, [["土木工事業", "土木工事業"], ["建築工事業", "建築工事業"], ["大工工事業", "大工工事業"], ["左官工事業", "左官工事業"], ["とび工事業", "とび工事業"], ["石工事業", "石工事業"]] ,class:"form-control" %></div>


				<br>

				<br>
				<br>
				<%= f.submit %>

				<% end %>
				
				</div>
			</div>
		</div>
	</div>

app/views/subs/search.html.erb
search.html.erb

app/views/subs/show.html.erb
<div class="topics2">
<div class="container">
	<div class="row">
		<div class="topics">

		<div class="col-sm-3 sub2">
		<%= link_to new_sub_path do %>
                <button type="button" class="square_btn1">下請けを募集する</button>
            <% end %>
            <%= link_to new_con_path do %>
                <button type="button" class="square_btn1">元請けを募集する</button>
            <% end %>

</div>
<div class="col-sm-offset-4">
			<div class="topicform">


						<h3><%= @sub.title  %></h3>
						<div>

<ul>
            <li>
                <dl>
                    <dt>工事内容</dt>
                    <dd><%= @sub.body  %></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>現場住所</dt>
                    <dd>
                       <%= @sub.address  %>
                    </dd>
                </dl>
            </li>
           
        </ul>




						</div>
</div>

					</div>
					</div>
					</div></div></div>

app/views/topics/index.html.erb
<div class="container">
<div class="maintopic">
	<div class="row">
		<div class="topics">

			<div class="col-sm-4 ">
			<div class="topicform">
				<%= form_for @newTopic, :url => {:action => 'create'} do |f| %>
				<div class="daimei">タイトル</div>
				<%= f.text_area :title ,rows: 3 ,cols:40 %>
				<div class="hondai">詳細</div>
				<%= f.text_area :body ,rows: 10 ,cols:40%>
				<br>
				<input type="checkbox" value="1" name="topic[job]">下請け募集
				<input type="checkbox" >元請け募集
<br>
<br>
				<%= f.submit %>

				<% end %>
				</div>
			</div>



			<div class="col-sm-7">
				<h3>職人募集や仕事探しの職人掲示板</h3>
				職人募集や仕事探しの職人掲示板
				建設業の職人さん向けの無料でご利用いただける掲示板です。 協力業者募集や求人、職人募集など、個別の工事や空き情報以外の用途に自由にお使いいただけます。 クロス職人、塗装職人、大工さん、リフォーム業者さん募集や元請け募集など毎日多くの書き込みが集まる職人掲示板です。



					<% @topics.each do |topic| %>

						<div class="topics1">
							<div class="posttitle"><%= link_to topic.title, topics_show_path(topic.id) %></div>
							<div class="postbody"> <%= topic.body %></div>


<%= attachment_image_tag topic.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", :size => "40x40" %>

<%=link_to topic.user.name,user_path(topic.user.id)%>

	<%= link_to  topics_show_path(topic.id) do %>
                <button type="button" class="square_btn2">詳細をみる</button>
            <% end %>

</div>
					<% end %>

			</div>
			</div>
</div>
		</div>
	</div>
</div>
</div>

app/views/topics/show.html.erb
<div class="topics2">
<div class="container">
	<div class="row">
		<div class="topics">

		<div class="col-sm-4">
<h3>返信フォーム</h3>


<%= form_for @newpost, :url => post_create_path do |f| %>
  <div class="daimei">名前</div>
  <p><%= f.text_area :name,rows: 1 ,cols:40%></p>
  <div class="hondai">本文</div>
  <p><%= f.text_area :body,rows: 10 ,cols:40 %></p>
  <%= f.hidden_field :topic_id %>
  <%= f.submit %>
<% end %>
</div>
</div>
<h3>個別スレッド詳細</h3>
<hr>
		<div class="col-sm-7">
			<div class="topicform1">


<div class="showmain">
<div class="showtitle"><h1><%= @topic.title %></h1></div>
<p class="showbody"><%= @topic.body %></p></div>
<hr>
<div class="comment">
<% @posts.each_with_index do |post , idx| %>
  <p>
     <%= post.name %> : <%= post.body %>
  </p>

<% end %>
</div>

</div>
</div>
<%= link_to topics_index_path do %>
                <button type="button" class="btn.btn_primary col-sm-3 col-sm-offset-6 modoru">スレッド一覧に戻る</button>
            <% end %>
</div>

</div>
</div>

app/views/users/info.html.erb
<div class="mypage_navi">
<div class="topics">


</div>
<div class="booksbody">

  <div>
    <% if notice %>
    <p id="notice"><%= notice %></p>
    <% end %>
  </div>


<aside class="col-md-4">
  <!-- 省略 -->
  <% if !current_user?(@user) && logged_in? %>
    <section class="message_box">
      <div id="messages">
        <%= render @messages %>
      </div>
    </section>
    <script type="text/javascript">
      var height = 0;
      $("div.message").each( function() {
        height += ($(this).height());
      });
      $('section.message_box').scrollTop(height);
    </script>
    <div class="message_form">
     <%= render 'messages/message_form',
       {from_user: current_user, to_user: @user, room_id: @room_id} %>
    </div>
  <% end %>
</aside>



  <h3>User Info</h3>
  <div class="container">
    <div class="row">

      <div class="col-xs-offset-1">

<!-- <div class="usershow col-xs-offset-3"></div> -->

   <table class="table">
          <tr class="table2">
          <td class="table1 table2">名前</td>

           <td class="table3"> <%= @user.name %></td>
         </tr>
        <tr class="table2">
        <td class="table1">郵便番号</td>
          <td class="table3"><%= @user.post %></td>
        </tr>
        <tr class="table2">
        <td class="table1">住所</td>
          <td class="table3"><%= @user.address %></td>
        </tr>
        </tr>
        <tr class="table2">
        <td class="table1">メールアドレス</td>
          <td class="table3"><%= @user.email %></td>
        </tr>
        <tr class="table2">
        <td class="table1">パスワード</td>
          <td class="table3"><%= @user.password %></td>
        </tr>
      <% if current_user.admin?%>
        <tr class="table2">
        <td class="table1">こいつ嫌い</td>
          <td class="table3"><%= link_to "削除", user_path, method: :delete, data: {confirm: '退会させてよろしいですか?'}, class: "taikai" %></td>
        </tr>
      <% else %>
        <tr class="table2">
        <td class="table1">退会</td>
          <td class="table3"><%= link_to "退会希望の方はこちら", user_registration_path, method: :delete, data: {confirm: 'go to hell?'}, class: "taikai" %></td>
        </tr>
      <% end %>

      </table>

        <%=button_to '編集', edit_user_path ,method: :get, class: 'btn btn-default botan1' %>
</div>
     </div>
     </div>
     </div>
     </div>

app/views/users/show.html.erb
<div class="topics">
  <div class="container">

    <div class="row">

      <div class="col-xs-offset-1">
<div class="information1">
<div class="information2">
自社情報</div>
<%= form_for(@user) do |f| %>

<div class="field">

   <table class="table2">
   <tr >
          <td class="edit"><b>現在の画像</b></td>

           <td class="edit">  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
          </td>
        </tr>
          <tr>
          <td class="edit"><b>会社名</b></td>

           <td> <%= @user.name %></td>
        </tr>
        <tr>
        <td class="edit"><b>郵便番号</b></td>
          <td> <%= @user.post %></td>
        </tr>
        <tr>
        <td class="edit"><b>住所</b></td>
          <td><%= @user.address %></td>
        </tr>
        <tr>
        <td class="edit"><b>メールアドレス</b></td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
        <td class="edit"><b>パスワード</b></td>
          <td><%= @user.password %></td>
        </tr>

<tr>
        <td class="edit"><b>退会</b></td>
          <td><%= link_to "退会希望の方はこちら", user_registration_path, method: :delete, data: {confirm: '退会しますか？'} %></td>
        </tr>
      </table>
        <% end %>
        <div class="back2">
         <%=button_to '編集', edit_user_path ,method: :get, class: 'btn btn-default ' %>
        </div>
        </div>
</div>
   </div>
     </div>
     </div>